tosca_definitions_version: tosca_simple_yaml_1_0

imports:
  - indigo_custom_types: https://raw.githubusercontent.com/mtangaro/tosca-types/laniakea-galaxy/custom_types.yaml

description: >
  Deploy Galaxy on a single Virtual Machine.
  The basic configuration includes CentOS 7, the selected Galaxy flavour, companion software and reference data.
  Configure, click on the "Submit" button, wait for the confirmation e-mail(s) and log in to your new Galaxy instance.
  If after some hours you do not receive any e-mail please be sure to check your SPAM BOX.

topology_template:
  inputs:

    #os_users:
    #  type: list
    #  description: prova
    #  entry_schema:
    #    type: tosca.datatypes.indigo.Users
    #  default: []

    instance_flavor:
      type: string
      description: instance flavor (num_cpu, memory, disk)
      default: large
    storage_size:
      type: string
      description: storage memory required for the instance
      default: 10 GB      

    os_distribution:
      type: string
      default: ubuntu
      description: Operating System distro
      constraints:
        - valid_values: [ "ubuntu", "centos" ]

    os_version:
      type: version
      default: 16.04
      description: Operating System distribution version
      constraints:
        - valid_values: [ 16.04, 7 ]

    admin_email:
      type: string
      description: email of the admin user
      default: admin@admin.com
    admin_api_key:
      type: string
      description: key to access the API with admin role
      default: not_very_secret_api_key
    user:
      type: string
      description: username to launch the galaxy daemon
      default: galaxy
    version:
      type: string
      description: galaxy version to install
      default: release_20.05
    instance_description:
      type: string
      description: galaxy instance description
      default: "ELIXIR"
    export_dir:
      type: string
      description: path to store galaxy data
      default: /export
    enable_galaxy_ie:
      type: boolean
      description: Enable Galaxy Interactive Environments (install docker)
      default: false

  node_templates:

    galaxy:
      type: tosca.nodes.indigo.GalaxyPortal
      properties:
        admin_email: { get_input: admin_email }
        admin_api_key: { get_input: admin_api_key }
        version: { get_input: version }
        instance_description: { get_input: instance_description }
        export_dir: { get_input: export_dir }
        enable_galaxy_ie: { get_input: enable_galaxy_ie}
      requirements:
        - lrms: local_lrms

    # type to describe a Galaxy not using any LRMS but using the local system
    local_lrms:
      type: tosca.nodes.indigo.LRMS.FrontEnd.Local
      requirements:
        - host: galaxy_server
 
    galaxy_server:
      type: tosca.nodes.indigo.Compute
      properties:
        os_users: [ {os_user_name: 'testuser', os_user_guid: '4001', os_user_add_to_sudoers: True, os_user_ssh_public_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDrm8mxOuqwP5XTHf685V9rqRXXg41F4isJvRr4h3MPDs8PgqZBzzjxEFyGpJ/Rgg4ACesGBZy+CbVVGtOveltKvgkpzyHIrh+vMay9z82eK2LMZEfmEPgw1BHdRifPZ1Qb7Zmj1nRk1EMWoNvbBxEc3/MSorWb+2SVMs+42EZ7QxavBmsU7zNU0Nd0e1xiqJ00VDWMnXullp/ieR9M4/XsSlS3oqxsxkAbY3eQYVMsnh64oiRw3lpYBkPyNtC/VSL5Cqig3CMaiK9AW8FjP1GwwqoMjL0H0Mkr0fY8eSSQ9Tcy5AqyaiPn7tmG0fSeNOFwxGkTzrujqlCiOkRSM1Yj marco@MacBook-Pro-di-Marco.local'} ]
      capabilities:
        endpoint:
          properties:
            network_name: PUBLIC
            private_ip: false
            ports:
              galaxyctl_api_port:
                protocol: tcp
                source: 5001
              luks_api_port:
                protocol: tcp
                source: 5000
              http_port:
                protocol: tcp
                source: 80
              ftp_port:
                protocol: tcp
                source: 21
              ftp_passive:
                protocol: tcp
                source_range: [ 30000, 30009 ]
        # Host container properties
        host:
         properties:
           instance_type: { get_input: instance_flavor }
        # Guest Operating System properties
        os:
          properties:
            #image: ubuntu-16.04
            #image: centos-7-2003
            distribution: { get_input: os_distribution }
            version: { get_input: os_version }
      requirements:
        # contextually this can only be a relationship type
        - local_storage:
            # capability is provided by Compute Node Type
            node: my_block_storage
            capability: tosca.capabilities.Attachment
            relationship:
              type: tosca.relationships.AttachesTo
              properties:
                location: { get_input: export_dir }
                device: hdb

    my_block_storage:
      type: tosca.nodes.BlockStorage
      properties:
        size: { get_input: storage_size }

  outputs:
    endpoint:
      #value: { concat: [ 'http://', get_attribute: [ galaxy_server, public_address, 0 ], '/galaxy' ] }
      value: { concat: [ 'http://', get_attribute: [ galaxy_server, public_address, 0 ] ] }
    node_ip:
      value: { get_attribute: [ galaxy_server, public_address, 0 ] }
